<?php
/*  -----------------------
    Admin settings page
    -----------------------
*/
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

 class GadlabMeteo {
	private $gadlab_meteo_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'gadlab_meteo_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'gadlab_meteo_page_init' ) );
	}

	public function gadlab_meteo_add_plugin_page() {
		add_options_page(
			'Gad Lab Meteo', // page_title
			'Gad Lab Meteo', // menu_title
			'manage_options', // capability
			'gadlab-meteo', // menu_slug
			array( $this, 'gadlab_meteo_create_admin_page' ) // function
		);
	}

	public function gadlab_meteo_create_admin_page() {
		$this->gadlab_meteo_options = get_option( 'gadlab_meteo_option_name' ); ?>

		<div class="wrap">
			<h2>Gad Lab Meteo · Preferences</h2>
			<p><strong>Hourly and daily weather forecasts for a given place in Switzerland.</strong></p>
			<p>Plugin’s page&nbsp;: <a href="https://github.com/gadlab/gadlab-meteo" target="_blank" title="GitHub Repository">gadlab-meteo</a><br>
			Data source&nbsp;: <a href="https://prevision-meteo.ch/" target="_blank" title="Clic opens in a new window...">prevision-meteo.ch</a></p>
			<h2>Settings</h2>
			<p><strong>Get json meteo data file from <a href="https://prevision-meteo.ch/service/" target="_blank">https://prevision-meteo.ch/service/</a></strong>&nbsp;:</p>
			<ol>
				<li>Enter the name or ZIP code of the location for which you wish to display the weather forecast and hit the <strong><em>[ENTER] key</em></strong>.<br>
				If necessary, select your location within the dropdown menu that appears below, to indicate the exact position.</li>
				<li>Scroll to third sections called <strong><em>JSON</em></strong> and clic in the field filled with the URL of json’s data. Select and copy the link.</li>
				<li>Go to your wordpress dashboard and choose menu <strong><em><a href="/wp-admin/options-general.php?page=gadlab-meteo">Settings > Gad Lab Meteo</a></em></strong>.</li>
				<li>Paste the link in the field named <strong><em>json file’s url</em></strong> under <strong><em>URL’s settings</em></strong> section.</li>
				<li><strong><em>Save changes</em></strong> at the bottom of the page.</li>
			</ol>
			<h2>Usage</h2>
			<p><strong>Add following shortcodes to your posts&nbsp;:</strong></p>
			<ul>
			<li><strong>[meteo type="today"]</strong> · Display today weather (short version)</li>
			<li><strong>[meteo type="hours"]</strong> · Display today weather informations in 24 hours format</li>
			<li><strong>[meteo type="forecast"]</strong> · Display weather forecast for today and the next three days</li>
			</ul>
			<p>&nbsp;</p>

			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'gadlab_meteo_option_group' );
					do_settings_sections( 'gadlab-meteo-admin' );
					submit_button();
				?>
			</form>
		
		</div>
	<?php }

	public function gadlab_meteo_page_init() {
		register_setting(
			'gadlab_meteo_option_group', // option_group
			'gadlab_meteo_option_name', // option_name
			array( $this, 'gadlab_meteo_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'url_setting_section', // id
			'<hr>URL’s settings', // title
			array( $this, 'gadlab_meteo_section_info' ), // callback
			'gadlab-meteo-admin' // page
		);

		add_settings_section(
			'css_setting_section', // id
			'<hr>CSS settings', // title
			array( $this, 'gadlab_meteo_section_info' ), // callback
			'gadlab-meteo-admin' // page
		);

		add_settings_field(
			'json_url', // id
			'json file’s url', // title
			array( $this, 'json_url_callback' ), // callback
			'gadlab-meteo-admin', // page
			'url_setting_section' // section
		);

		add_settings_field(
			'detailed_page', // id
			'Detailed page’s url', // title
			array( $this, 'detailed_page_callback' ), // callback
			'gadlab-meteo-admin', // page
			'url_setting_section' // section
		);

		add_settings_field(
			'color_text_display', // id
			'Color text display', // title
			array( $this, 'color_text_display_callback' ), // callback
			'gadlab-meteo-admin', // page
			'css_setting_section' // section
		);

		add_settings_field(
			'warm_color', // id
			'Warm color in hexadécimal', // title
			array( $this, 'warm_color_callback' ), // callback
			'gadlab-meteo-admin', // page
			'css_setting_section' // section
		);

		add_settings_field(
			'cold_color', // id
			'Cold color in hexadécimal', // title
			array( $this, 'cold_color_callback' ), // callback
			'gadlab-meteo-admin', // page
			'css_setting_section' // section
		);
	}

	public function gadlab_meteo_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['json_url'] ) ) {
			$sanitary_values['json_url'] = sanitize_text_field( $input['json_url'] );
		}

		// detailed_page
		if ( isset( $input['detailed_page'] ) ) {
			$sanitary_values['detailed_page'] = sanitize_text_field( $input['detailed_page'] );
		}
		
		if ( isset( $input['color_text_display'] ) ) {
			$sanitary_values['color_text_display'] = $input['color_text_display'];
		}

		if ( isset( $input['warm_color'] ) ) {
			$sanitary_values['warm_color'] = sanitize_text_field( $input['warm_color'] );
		}

		if ( isset( $input['cold_color'] ) ) {
			$sanitary_values['cold_color'] = sanitize_text_field( $input['cold_color'] );
		}

		return $sanitary_values;
	}

	public function gadlab_meteo_section_info() {
		
	}

	public function json_url_callback() {
		printf(
			'<input class="regular-text" type="text" name="gadlab_meteo_option_name[json_url]" id="json_url" value="%s">',
			isset( $this->gadlab_meteo_options['json_url'] ) ? esc_attr( $this->gadlab_meteo_options['json_url']) : ''
		);
	}

	// detailed_page
	public function detailed_page_callback() {
		printf(
			'<input class="regular-text" type="text" name="gadlab_meteo_option_name[detailed_page]" id="detailed_page" value="%s">',
			isset( $this->gadlab_meteo_options['detailed_page'] ) ? esc_attr( $this->gadlab_meteo_options['detailed_page']) : ''
		);
	}

	public function color_text_display_callback() {
		?> <fieldset><?php $checked = ( isset( $this->gadlab_meteo_options['color_text_display'] ) && $this->gadlab_meteo_options['color_text_display'] === 'dark' ) ? 'checked' : '' ; ?>
		<label for="color_text_display-0"><input type="radio" name="gadlab_meteo_option_name[color_text_display]" id="color_text_display-0" value="dark" <?php echo $checked; ?>> Dark text on light background</label><br>
		<?php $checked = ( isset( $this->gadlab_meteo_options['color_text_display'] ) && $this->gadlab_meteo_options['color_text_display'] === 'light' ) ? 'checked' : '' ; ?>
		<label for="color_text_display-1"><input type="radio" name="gadlab_meteo_option_name[color_text_display]" id="color_text_display-1" value="light" <?php echo $checked; ?>> Light text on dark background</label></fieldset> <?php
	}

	public function warm_color_callback() {
		printf(
			'<input class="regular-text" type="text" name="gadlab_meteo_option_name[warm_color]" id="warm_color" value="%s">',
			isset( $this->gadlab_meteo_options['warm_color'] ) ? esc_attr( $this->gadlab_meteo_options['warm_color']) : ''
		);
	}

	public function cold_color_callback() {
		printf(
			'<input class="regular-text" type="text" name="gadlab_meteo_option_name[cold_color]" id="cold_color" value="%s">',
			isset( $this->gadlab_meteo_options['cold_color'] ) ? esc_attr( $this->gadlab_meteo_options['cold_color']) : ''
		);
	}

}
if ( is_admin() )
	$gadlab_meteo = new GadlabMeteo();

/* 
 * Retrieve this value with:
 * $gadlab_meteo_options = get_option( 'gadlab_meteo_option_name' ); // Array of All Options
 * $json_url = $gadlab_meteo_options['json_url']; // json file’s url
 * $detailed_page = $gadlab_meteo_options['detailed_page']; // Detailed page’s url
 * $color_text_display = $gadlab_meteo_options['color_text_display']; // Color text display
 * $warm_color = $gadlab_meteo_options['warm_color']; // Warm color in hexadécimal
 * $cold_color = $gadlab_meteo_options['cold_color']; // Cold color in hexadécimal
 */
