<?php
/*  -----------------------
    Admin settings page
    -----------------------
*/
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

 class GadlabMeteo {
	private $gadlab_meteo_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'gadlab_meteo_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'gadlab_meteo_page_init' ) );
	}

	public function gadlab_meteo_add_plugin_page() {
		add_options_page(
			'Gad Lab Meteo', // page_title
			'Gad Lab Meteo', // menu_title
			'manage_options', // capability
			'gadlab-meteo', // menu_slug
			array( $this, 'gadlab_meteo_create_admin_page' ) // function
		);
	}

	public function gadlab_meteo_create_admin_page() {
		$this->gadlab_meteo_options = get_option( 'gadlab_meteo_option_name' ); ?>

		<div class="wrap">
			<h2>Gad Lab Meteo · Administration</h2>
			<p>Texte description of what the plugins does.</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'gadlab_meteo_option_group' );
					do_settings_sections( 'gadlab-meteo-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function gadlab_meteo_page_init() {
		register_setting(
			'gadlab_meteo_option_group', // option_group
			'gadlab_meteo_option_name', // option_name
			array( $this, 'gadlab_meteo_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'gadlab_meteo_setting_section', // id
			'Settings', // title
			array( $this, 'gadlab_meteo_section_info' ), // callback
			'gadlab-meteo-admin' // page
		);

		add_settings_field(
			'json_file_s_url_0', // id
			'json file’s url', // title
			array( $this, 'json_file_s_url_0_callback' ), // callback
			'gadlab-meteo-admin', // page
			'gadlab_meteo_setting_section' // section
		);

		add_settings_field(
			'color_text_display_1', // id
			'Color text display', // title
			array( $this, 'color_text_display_1_callback' ), // callback
			'gadlab-meteo-admin', // page
			'gadlab_meteo_setting_section' // section
		);

		add_settings_field(
			'warm_color_in_hexadecimal_2', // id
			'Warm color in hexadécimal', // title
			array( $this, 'warm_color_in_hexadecimal_2_callback' ), // callback
			'gadlab-meteo-admin', // page
			'gadlab_meteo_setting_section' // section
		);

		add_settings_field(
			'cold_color_in_hexadecimal_3', // id
			'Cold color in hexadécimal', // title
			array( $this, 'cold_color_in_hexadecimal_3_callback' ), // callback
			'gadlab-meteo-admin', // page
			'gadlab_meteo_setting_section' // section
		);
	}

	public function gadlab_meteo_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['json_file_s_url_0'] ) ) {
			$sanitary_values['json_file_s_url_0'] = sanitize_text_field( $input['json_file_s_url_0'] );
		}

		if ( isset( $input['color_text_display_1'] ) ) {
			$sanitary_values['color_text_display_1'] = $input['color_text_display_1'];
		}

		if ( isset( $input['warm_color_in_hexadecimal_2'] ) ) {
			$sanitary_values['warm_color_in_hexadecimal_2'] = sanitize_text_field( $input['warm_color_in_hexadecimal_2'] );
		}

		if ( isset( $input['cold_color_in_hexadecimal_3'] ) ) {
			$sanitary_values['cold_color_in_hexadecimal_3'] = sanitize_text_field( $input['cold_color_in_hexadecimal_3'] );
		}

		return $sanitary_values;
	}

	public function gadlab_meteo_section_info() {
		
	}

	public function json_file_s_url_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="gadlab_meteo_option_name[json_file_s_url_0]" id="json_file_s_url_0" value="%s">',
			isset( $this->gadlab_meteo_options['json_file_s_url_0'] ) ? esc_attr( $this->gadlab_meteo_options['json_file_s_url_0']) : ''
		);
	}

	public function color_text_display_1_callback() {
		?> <fieldset><?php $checked = ( isset( $this->gadlab_meteo_options['color_text_display_1'] ) && $this->gadlab_meteo_options['color_text_display_1'] === 'dark' ) ? 'checked' : '' ; ?>
		<label for="color_text_display_1-0"><input type="radio" name="gadlab_meteo_option_name[color_text_display_1]" id="color_text_display_1-0" value="dark" <?php echo $checked; ?>> Dark text on light background</label><br>
		<?php $checked = ( isset( $this->gadlab_meteo_options['color_text_display_1'] ) && $this->gadlab_meteo_options['color_text_display_1'] === 'light' ) ? 'checked' : '' ; ?>
		<label for="color_text_display_1-1"><input type="radio" name="gadlab_meteo_option_name[color_text_display_1]" id="color_text_display_1-1" value="light" <?php echo $checked; ?>> Light text on dark background</label></fieldset> <?php
	}

	public function warm_color_in_hexadecimal_2_callback() {
		printf(
			'<input class="regular-text" type="text" name="gadlab_meteo_option_name[warm_color_in_hexadecimal_2]" id="warm_color_in_hexadecimal_2" value="%s">',
			isset( $this->gadlab_meteo_options['warm_color_in_hexadecimal_2'] ) ? esc_attr( $this->gadlab_meteo_options['warm_color_in_hexadecimal_2']) : ''
		);
	}

	public function cold_color_in_hexadecimal_3_callback() {
		printf(
			'<input class="regular-text" type="text" name="gadlab_meteo_option_name[cold_color_in_hexadecimal_3]" id="cold_color_in_hexadecimal_3" value="%s">',
			isset( $this->gadlab_meteo_options['cold_color_in_hexadecimal_3'] ) ? esc_attr( $this->gadlab_meteo_options['cold_color_in_hexadecimal_3']) : ''
		);
	}

}
if ( is_admin() )
	$gadlab_meteo = new GadlabMeteo();

/* 
 * Retrieve this value with:
 * $gadlab_meteo_options = get_option( 'gadlab_meteo_option_name' ); // Array of All Options
 * $json_file_s_url_0 = $gadlab_meteo_options['json_file_s_url_0']; // json file’s url
 * $color_text_display_1 = $gadlab_meteo_options['color_text_display_1']; // Color text display
 * $warm_color_in_hexadecimal_2 = $gadlab_meteo_options['warm_color_in_hexadecimal_2']; // Warm color in hexadécimal
 * $cold_color_in_hexadecimal_3 = $gadlab_meteo_options['cold_color_in_hexadecimal_3']; // Cold color in hexadécimal
 */
